language: php

php:
  - '7.2'

services:
  - docker

before_script:
  - docker build -t test-php:latest . && docker-compose up
  - docker ps
  - docker exec -it  test-php bash
  - php artisan migrate && php artisan passport:install
  - php artisan db:seed && exit

script:
  - php vendor/bin/codecept run

