language: php

php:
  - '7.2'

install:
  - cp .env.travis .env
  - mysql -e 'create database homestead_test;'
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate

before_script:
  - php artisan serve --port=9595 &
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost:9595 &


script:
  - php vendor/bin/codecept run